// gg_ids.c - GENERATED by tools/make_atlas.py, do not edit.
//
// Prop geometry, for the simulation's collision.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#include "core/gg_ids.h"

const gg_prop_size GG_PROP_SIZE[GG_PROP_COUNT] = {
    [GG_PROP_TREE_OAK] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_ELM] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_TALL] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_PINE] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_FIR] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_BARE] = { 3, 5, 1, 4, 1, 1, 255, 0, 0 },
    [GG_PROP_STUMP] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_ROUND] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_LEAFY] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_CONIFER] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_REEDS] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_FERN] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_LILYPAD] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_CATTAILS] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BARREL] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_CRATE] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_TABLE] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_LAMP] = { 1, 2, 0, 1, 1, 1, 255, 0, 4 },
    [GG_PROP_TORCH_WALL] = { 1, 2, 0, 1, 1, 1, 255, 0, 4 },
    [GG_PROP_CAMPFIRE] = { 1, 1, 0, 0, 1, 1, 255, 0, 5 },
    [GG_PROP_HOUSE_BRICK_A] = { 8, 7, 3, 5, 6, 6, 1, 1, 0 },
    [GG_PROP_HOUSE_BRICK_B] = { 6, 6, 2, 5, 4, 6, 2, 1, 0 },
    [GG_PROP_HOUSE_PANELED] = { 5, 5, 2, 4, 5, 5, 3, 1, 0 },
};
