// gg_ids.h - GENERATED by tools/make_atlas.py, do not edit.
//
// The content vocabulary shared by the simulation and the renderer.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#ifndef GG_IDS_H
#define GG_IDS_H

#include <stdint.h>

typedef enum {
    GG_TILE_GRASS,
    GG_TILE_GRASS_WORN,
    GG_TILE_DIRT,
    GG_TILE_EARTH_DARK,
    GG_TILE_FARMLAND,
    GG_TILE_ROAD,
    GG_TILE_SAND,
    GG_TILE_DESERT,
    GG_TILE_WATER,
    GG_TILE_WATER_DEEP,
    GG_TILE_MOUNTAIN,
    GG_TILE_CLIFF,
    GG_TILE_COUNT
} gg_tile_id;

typedef enum {
    GG_PROP_TREE_OAK,
    GG_PROP_TREE_ELM,
    GG_PROP_TREE_TALL,
    GG_PROP_TREE_PINE,
    GG_PROP_TREE_FIR,
    GG_PROP_TREE_BARE,
    GG_PROP_STUMP,
    GG_PROP_BUSH_ROUND,
    GG_PROP_BUSH_LEAFY,
    GG_PROP_BUSH_CONIFER,
    GG_PROP_REEDS,
    GG_PROP_FERN,
    GG_PROP_LILYPAD,
    GG_PROP_CATTAILS,
    GG_PROP_HOUSE_BRICK_A,
    GG_PROP_HOUSE_BRICK_B,
    GG_PROP_HOUSE_PANELED,
    GG_PROP_COUNT
} gg_prop_id;

typedef enum {
    GG_ACTOR_AVATAR,
    GG_ACTOR_GUARD,
    GG_ACTOR_MERCHANT,
    GG_ACTOR_HEALER,
    GG_ACTOR_MAGE,
    GG_ACTOR_ELDER,
    GG_ACTOR_COUNT
} gg_actor_id;

// Row order within an actor's block, matching LPC's Walk.png.
typedef enum { GG_FACE_UP, GG_FACE_LEFT, GG_FACE_DOWN, GG_FACE_RIGHT } gg_facing;

#define GG_ACTOR_FRAMES  8
#define GG_ACTOR_DIRS    4

// A prop's geometry, which the simulation needs for collision and
// the renderer for placement.
//
//   tiles_w/h   the sprite, in tiles
//   anchor_x/y  the sprite cell that sits on the map cell the prop
//               occupies - always the footprint's bottom centre
//   foot_w/h    the footprint: what stands on the ground and blocks.
//               The sprite may be larger and overhang the rows above,
//               which is how a roof covers tiles you can walk behind.
//   door_dx     column within the footprint that is a doorway, or
//               GG_NO_DOOR. That cell stays walkable.
#define GG_NO_DOOR 255
typedef struct {
    uint8_t tiles_w, tiles_h;
    uint8_t anchor_x, anchor_y;
    uint8_t foot_w, foot_h;
    uint8_t door_dx;
} gg_prop_size;
extern const gg_prop_size GG_PROP_SIZE[GG_PROP_COUNT];

#endif // GG_IDS_H
