// gg_ids.c - GENERATED by tools/make_atlas.py, do not edit.
//
// Prop geometry and the item table, for the simulation.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#include "core/gg_ids.h"

const gg_prop_size GG_PROP_SIZE[GG_PROP_COUNT] = {
    [GG_PROP_TREE_OAK] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_ELM] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_TALL] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_PINE] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_FIR] = { 3, 4, 1, 3, 1, 1, 255, 0, 0 },
    [GG_PROP_TREE_BARE] = { 3, 5, 1, 4, 1, 1, 255, 0, 0 },
    [GG_PROP_STUMP] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_ROUND] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_LEAFY] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BUSH_CONIFER] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_REEDS] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_FERN] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_LILYPAD] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_CATTAILS] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_BARREL] = { 1, 2, 0, 1, 1, 1, 255, 0, 0 },
    [GG_PROP_CRATE] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_TABLE] = { 1, 1, 0, 0, 1, 1, 255, 0, 0 },
    [GG_PROP_LAMP] = { 1, 2, 0, 1, 1, 1, 255, 0, 4 },
    [GG_PROP_TORCH_WALL] = { 1, 2, 0, 1, 1, 1, 255, 0, 4 },
    [GG_PROP_CAMPFIRE] = { 1, 1, 0, 0, 1, 1, 255, 0, 5 },
    [GG_PROP_HOUSE_BRICK_A] = { 8, 7, 3, 5, 6, 6, 1, 1, 0 },
    [GG_PROP_HOUSE_BRICK_B] = { 6, 6, 2, 5, 4, 6, 2, 1, 0 },
    [GG_PROP_HOUSE_PANELED] = { 5, 5, 2, 4, 5, 5, 3, 1, 0 },
};

const gg_item_def GG_ITEM[GG_ITEM_COUNT] = {
    [GG_ITEM_BREAD] = {
        "BREAD",
        "a loaf of bread", "loaves of bread", "bread",
        1, 1, 40, 1,
        GG_USE_EAT, 4, GG_SLOT_NONE, 0, 5,
        0, 0, 0,
    },
    [GG_ITEM_APPLE] = {
        "APPLE",
        "an apple", "apples", "apples",
        1, 1, 15, 1,
        GG_USE_EAT, 2, GG_SLOT_NONE, 0, 2,
        0, 0, 0,
    },
    [GG_ITEM_POTION] = {
        "POTION",
        "a phial of red liquor", "phials of red liquor", "phials",
        1, 1, 60, 1,
        GG_USE_DRINK, 15, GG_SLOT_NONE, 0, 40,
        0, 0, 0,
    },
    [GG_ITEM_TORCH] = {
        "TORCH",
        "a torch", "torches", "torches",
        1, 2, 90, 1,
        GG_USE_NONE, 0, GG_SLOT_LIGHT, 4, 8,
        0, 0, 0,
    },
    [GG_ITEM_GOLD] = {
        "GOLD",
        "a gold coin", "gold coins", "gold",
        1, 1, 1, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 10,
        0, 0, 0,
    },
    [GG_ITEM_SILVER] = {
        "SILVER",
        "a bar of silver", "bars of silver", "silver",
        1, 1, 400, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 200,
        0, 0, 0,
    },
    [GG_ITEM_HAMMER] = {
        "HAMMER",
        "a smith's hammer", "smith's hammers", "hammer",
        1, 1, 350, 0,
        GG_USE_NONE, 0, GG_SLOT_WEAPON, 0, 60,
        5, 0, 0,
    },
    [GG_ITEM_STONE] = {
        "STONE",
        "a throwing stone", "throwing stones", "stones",
        1, 1, 30, 1,
        GG_USE_NONE, 0, GG_SLOT_WEAPON, 0, 1,
        2, 0, 5,
    },
    [GG_ITEM_GINSENG] = {
        "GINSENG",
        "a ginseng root", "ginseng roots", "ginseng",
        1, 1, 5, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 6,
        0, 0, 0,
    },
    [GG_ITEM_NIGHTSHADE] = {
        "NIGHTSHADE",
        "a sprig of nightshade", "sprigs of nightshade", "nightshade",
        1, 1, 3, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 20,
        0, 0, 0,
    },
    [GG_ITEM_BLOODMOSS] = {
        "BLOODMOSS",
        "a tuft of blood moss", "tufts of blood moss", "blood moss",
        1, 1, 3, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 10,
        0, 0, 0,
    },
    [GG_ITEM_ASH] = {
        "ASH",
        "a pinch of sulphurous ash", "pinches of sulphurous ash", "ash",
        1, 1, 2, 1,
        GG_USE_NONE, 0, GG_SLOT_NONE, 0, 4,
        0, 0, 0,
    },
    [GG_ITEM_SHIELD] = {
        "SHIELD",
        "a wooden shield", "wooden shields", "shield",
        1, 1, 500, 0,
        GG_USE_NONE, 0, GG_SLOT_ARMOUR, 0, 80,
        0, 3, 0,
    },
};
