// gg_ids.h - GENERATED by tools/make_atlas.py, do not edit.
//
// The content vocabulary shared by the simulation and the renderer.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#ifndef GG_IDS_H
#define GG_IDS_H

#include <stdint.h>

typedef enum {
    GG_TILE_GRASS,
    GG_TILE_GRASS_WORN,
    GG_TILE_DIRT,
    GG_TILE_EARTH_DARK,
    GG_TILE_FARMLAND,
    GG_TILE_ROAD,
    GG_TILE_SAND,
    GG_TILE_DESERT,
    GG_TILE_WATER,
    GG_TILE_WATER_DEEP,
    GG_TILE_MOUNTAIN,
    GG_TILE_CLIFF,
    GG_TILE_FLOOR_WOOD,
    GG_TILE_WALL_BRICK,
    GG_TILE_COUNT
} gg_tile_id;

typedef enum {
    GG_PROP_TREE_OAK,
    GG_PROP_TREE_ELM,
    GG_PROP_TREE_TALL,
    GG_PROP_TREE_PINE,
    GG_PROP_TREE_FIR,
    GG_PROP_TREE_BARE,
    GG_PROP_STUMP,
    GG_PROP_BUSH_ROUND,
    GG_PROP_BUSH_LEAFY,
    GG_PROP_BUSH_CONIFER,
    GG_PROP_REEDS,
    GG_PROP_FERN,
    GG_PROP_LILYPAD,
    GG_PROP_CATTAILS,
    GG_PROP_BARREL,
    GG_PROP_CRATE,
    GG_PROP_TABLE,
    GG_PROP_LAMP,
    GG_PROP_TORCH_WALL,
    GG_PROP_CAMPFIRE,
    GG_PROP_HOUSE_BRICK_A,
    GG_PROP_HOUSE_BRICK_B,
    GG_PROP_HOUSE_PANELED,
    GG_PROP_COUNT
} gg_prop_id;

typedef enum {
    GG_ACTOR_AVATAR,
    GG_ACTOR_GUARD,
    GG_ACTOR_MERCHANT,
    GG_ACTOR_HEALER,
    GG_ACTOR_MAGE,
    GG_ACTOR_ELDER,
    GG_ACTOR_BRIGAND,
    GG_ACTOR_OUTLAW,
    GG_ACTOR_COUNT
} gg_actor_id;

typedef enum {
    GG_ITEM_BREAD,
    GG_ITEM_APPLE,
    GG_ITEM_POTION,
    GG_ITEM_TORCH,
    GG_ITEM_GOLD,
    GG_ITEM_SILVER,
    GG_ITEM_HAMMER,
    GG_ITEM_STONE,
    GG_ITEM_GINSENG,
    GG_ITEM_NIGHTSHADE,
    GG_ITEM_BLOODMOSS,
    GG_ITEM_ASH,
    GG_ITEM_SHIELD,
    GG_ITEM_COUNT
} gg_item_id;

// What using a thing does.
typedef enum { GG_USE_NONE, GG_USE_EAT, GG_USE_DRINK } gg_item_use;

// Where a thing can be held. Each slot has to do something: a
// torch lights, a weapon strikes, a shield turns a blow aside.
typedef enum {
    GG_SLOT_NONE, GG_SLOT_LIGHT, GG_SLOT_WEAPON, GG_SLOT_ARMOUR,
    GG_SLOT_COUNT
} gg_slot_id;

// A kind of carryable thing.
//
//   id              the name a data file calls it by - GINSENG - as
//                   opposed to the prose, which has spaces in it
//   one/many/short  how it reads in a sentence, and bare in a list
//   tiles_w/h       the sprite, in tiles, drawn from its bottom row
//   weight          in HUNDREDTHS OF A STONE - the unit that makes a
//                   coin weigh 1 and stay an integer
//   stack           whether several share one slot in the pack
//   use/heal        what using it does, and how much health it gives
//   slot/light      where it is held, and how far it lights while held
//   value           worth in copper, for when there is trade
//   damage/guard    what it adds to a blow, what it turns aside
//   reach           how many tiles away it strikes; 0 is arm's length,
//                   and anything further is thrown and left where it lands
typedef struct {
    const char *id;
    const char *one, *many, *short_name;
    uint8_t  tiles_w, tiles_h;
    uint16_t weight;
    uint8_t  stack;
    uint8_t  use, heal;
    uint8_t  slot, light;
    uint16_t value;
    uint8_t  damage, guard, reach;
} gg_item_def;
extern const gg_item_def GG_ITEM[GG_ITEM_COUNT];

// The name a data file calls each of these by - the bestiary says
// BRIGAND and gets the sprite, without a number nobody can check.
extern const char *const GG_ACTOR_ID_NAME[GG_ACTOR_COUNT];

// The same, for what a map is made of. A map written as text says
// GRASS and TREE_OAK; a number in a file nobody can read is how a
// format stops being editable by a person.
extern const char *const GG_TILE_ID_NAME[GG_TILE_COUNT];
extern const char *const GG_PROP_ID_NAME[GG_PROP_COUNT];

// Row order within an actor's block, matching LPC's Walk.png.
typedef enum { GG_FACE_UP, GG_FACE_LEFT, GG_FACE_DOWN, GG_FACE_RIGHT } gg_facing;

// The largest radius any light may have. The renderer scans a box
// this big around each cell looking for emitters, so a brighter one
// would simply be clipped - this script refuses one rather than let
// that happen. Emitted here rather than written in two files that
// have to agree by hand, and here rather than in the renderer so the
// simulation can bound a spell without reaching across the layer.
#define GG_LIGHT_MAX_RADIUS 6

#define GG_ACTOR_FRAMES  8
#define GG_ACTOR_DIRS    4

// A prop's geometry, which the simulation needs for collision and
// the renderer for placement.
//
//   tiles_w/h   the sprite, in tiles
//   anchor_x/y  the sprite cell that sits on the map cell the prop
//               occupies - always the footprint's bottom centre
//   foot_w/h    the footprint: what stands on the ground and blocks.
//               The sprite may be larger and overhang the rows above,
//               which is how a roof covers tiles you can walk behind.
//   door_dx     column within the footprint that is a doorway, or
//               GG_NO_DOOR. That cell stays walkable.
#define GG_NO_DOOR 255
typedef struct {
    uint8_t tiles_w, tiles_h;
    uint8_t anchor_x, anchor_y;
    uint8_t foot_w, foot_h;
    uint8_t door_dx;
    uint8_t hollow;   // a building: walls around a walkable interior
    uint8_t light;    // how far it lights the world, in tiles; 0 for most
} gg_prop_size;
extern const gg_prop_size GG_PROP_SIZE[GG_PROP_COUNT];

#endif // GG_IDS_H
