// gg_atlas.h - GENERATED by tools/make_atlas.py, do not edit.
//
// Where every sprite sits inside the four atlas textures in assets/.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#ifndef GG_ATLAS_H
#define GG_ATLAS_H

#include <stdint.h>
#include "core/gg_ids.h"

typedef struct { int16_t x, y, w, h; } gg_rect;

static const gg_rect GG_TILE_RECT[GG_TILE_COUNT] = {
    [GG_TILE_GRASS] = {    0,    0,  32,  32 },
    [GG_TILE_GRASS_WORN] = {   32,    0,  32,  32 },
    [GG_TILE_DIRT] = {   64,    0,  32,  32 },
    [GG_TILE_EARTH_DARK] = {   96,    0,  32,  32 },
    [GG_TILE_FARMLAND] = {  128,    0,  32,  32 },
    [GG_TILE_ROAD] = {  160,    0,  32,  32 },
    [GG_TILE_SAND] = {  192,    0,  32,  32 },
    [GG_TILE_DESERT] = {  224,    0,  32,  32 },
    [GG_TILE_WATER] = {    0,   32,  32,  32 },
    [GG_TILE_WATER_DEEP] = {   32,   32,  32,  32 },
    [GG_TILE_MOUNTAIN] = {   64,   32,  32,  32 },
    [GG_TILE_CLIFF] = {   96,   32,  32,  32 },
    [GG_TILE_FLOOR_WOOD] = {  128,   32,  32,  32 },
    [GG_TILE_WALL_BRICK] = {  160,   32,  32,  32 },
};

static const gg_rect GG_PROP_RECT[GG_PROP_COUNT] = {
    [GG_PROP_TREE_OAK] = {    0,    0,  96, 128 },
    [GG_PROP_TREE_ELM] = {   96,    0,  96, 128 },
    [GG_PROP_TREE_TALL] = {  192,    0,  96, 128 },
    [GG_PROP_TREE_PINE] = {  288,    0,  96, 128 },
    [GG_PROP_TREE_FIR] = {  384,    0,  96, 128 },
    [GG_PROP_TREE_BARE] = {  480,    0,  96, 160 },
    [GG_PROP_STUMP] = {  576,    0,  32,  32 },
    [GG_PROP_BUSH_ROUND] = {  608,    0,  32,  64 },
    [GG_PROP_BUSH_LEAFY] = {    0,  160,  32,  64 },
    [GG_PROP_BUSH_CONIFER] = {   32,  160,  32,  64 },
    [GG_PROP_REEDS] = {   64,  160,  32,  64 },
    [GG_PROP_FERN] = {   96,  160,  32,  64 },
    [GG_PROP_LILYPAD] = {  128,  160,  32,  32 },
    [GG_PROP_CATTAILS] = {  160,  160,  32,  64 },
    [GG_PROP_BARREL] = {  192,  160,  32,  64 },
    [GG_PROP_CRATE] = {  224,  160,  32,  32 },
    [GG_PROP_TABLE] = {  256,  160,  32,  32 },
    [GG_PROP_HOUSE_BRICK_A] = {  288,  160, 256, 224 },
    [GG_PROP_HOUSE_BRICK_B] = {    0,  384, 192, 192 },
    [GG_PROP_HOUSE_PANELED] = {  192,  384, 160, 160 },
};

#define GG_ACTOR_FRAME   64
// Top-left of each actor's block; add facing*FRAME to y, frame*FRAME to x.
static const gg_rect GG_ACTOR_RECT[GG_ACTOR_COUNT] = {
    [GG_ACTOR_AVATAR] = {    0,    0,  64,  64 },
    [GG_ACTOR_GUARD] = {    0,  256,  64,  64 },
    [GG_ACTOR_MERCHANT] = {    0,  512,  64,  64 },
    [GG_ACTOR_HEALER] = {    0,  768,  64,  64 },
    [GG_ACTOR_MAGE] = {    0, 1024,  64,  64 },
    [GG_ACTOR_ELDER] = {    0, 1280,  64,  64 },
};

// --- edge sets: 3x3 blob rings, in atlas_edges.png ---
// Index order, which is what gg_render computes from a neighbour mask:
//     0 NW  1 N  2 NE / 3 W  4 C  5 E / 6 SW  7 S  8 SE
typedef enum {
    GG_EDGE_WATER_GRASS,
    GG_EDGE_WATER_SAND,
    GG_EDGE_WATER_DEEP,
    GG_EDGE_COUNT
} gg_edge_id;

#define GG_EDGE_NW 0
#define GG_EDGE_N  1
#define GG_EDGE_NE 2
#define GG_EDGE_W  3
#define GG_EDGE_C  4
#define GG_EDGE_E  5
#define GG_EDGE_SW 6
#define GG_EDGE_S  7
#define GG_EDGE_SE 8
// Concave corners, composed at bake time - the sheets have none.
#define GG_EDGE_IN_NW 9
#define GG_EDGE_IN_NE 10
#define GG_EDGE_IN_SW 11
#define GG_EDGE_IN_SE 12
#define GG_EDGE_PIECES 13

static const gg_rect GG_EDGE_RECT[GG_EDGE_COUNT][GG_EDGE_PIECES] = {
    [GG_EDGE_WATER_GRASS] = { {    0,    0,  32,  32 }, {   32,    0,  32,  32 }, {   64,    0,  32,  32 }, {   96,    0,  32,  32 }, {  128,    0,  32,  32 }, {  160,    0,  32,  32 }, {  192,    0,  32,  32 }, {  224,    0,  32,  32 }, {  256,    0,  32,  32 }, {  288,    0,  32,  32 }, {  320,    0,  32,  32 }, {  352,    0,  32,  32 }, {  384,    0,  32,  32 } },
    [GG_EDGE_WATER_SAND] = { {    0,   32,  32,  32 }, {   32,   32,  32,  32 }, {   64,   32,  32,  32 }, {   96,   32,  32,  32 }, {  128,   32,  32,  32 }, {  160,   32,  32,  32 }, {  192,   32,  32,  32 }, {  224,   32,  32,  32 }, {  256,   32,  32,  32 }, {  288,   32,  32,  32 }, {  320,   32,  32,  32 }, {  352,   32,  32,  32 }, {  384,   32,  32,  32 } },
    [GG_EDGE_WATER_DEEP] = { {    0,   64,  32,  32 }, {   32,   64,  32,  32 }, {   64,   64,  32,  32 }, {   96,   64,  32,  32 }, {  128,   64,  32,  32 }, {  160,   64,  32,  32 }, {  192,   64,  32,  32 }, {  224,   64,  32,  32 }, {  256,   64,  32,  32 }, {  288,   64,  32,  32 }, {  320,   64,  32,  32 }, {  352,   64,  32,  32 }, {  384,   64,  32,  32 } },
};

// --- overlay rings: land meeting land, drawn OVER a base tile ---
// Same 13-piece indexing as the edge sets: piece k means "the
// other terrain lies in direction k". In atlas_overlays.png.
typedef enum {
    GG_OVERLAY_GRASS,
    GG_OVERLAY_FARMLAND,
    GG_OVERLAY_DIRT,
    GG_OVERLAY_ROAD,
    GG_OVERLAY_SAND,
    GG_OVERLAY_DESERT,
    GG_OVERLAY_COUNT
} gg_overlay_id;

static const gg_rect GG_OVERLAY_RECT[GG_OVERLAY_COUNT][GG_EDGE_PIECES] = {
    [GG_OVERLAY_GRASS] = { {    0,    0,  32,  32 }, {   32,    0,  32,  32 }, {   64,    0,  32,  32 }, {   96,    0,  32,  32 }, {  128,    0,  32,  32 }, {  160,    0,  32,  32 }, {  192,    0,  32,  32 }, {  224,    0,  32,  32 }, {  256,    0,  32,  32 }, {  288,    0,  32,  32 }, {  320,    0,  32,  32 }, {  352,    0,  32,  32 }, {  384,    0,  32,  32 } },
    [GG_OVERLAY_FARMLAND] = { {    0,   32,  32,  32 }, {   32,   32,  32,  32 }, {   64,   32,  32,  32 }, {   96,   32,  32,  32 }, {  128,   32,  32,  32 }, {  160,   32,  32,  32 }, {  192,   32,  32,  32 }, {  224,   32,  32,  32 }, {  256,   32,  32,  32 }, {  288,   32,  32,  32 }, {  320,   32,  32,  32 }, {  352,   32,  32,  32 }, {  384,   32,  32,  32 } },
    [GG_OVERLAY_DIRT] = { {    0,   64,  32,  32 }, {   32,   64,  32,  32 }, {   64,   64,  32,  32 }, {   96,   64,  32,  32 }, {  128,   64,  32,  32 }, {  160,   64,  32,  32 }, {  192,   64,  32,  32 }, {  224,   64,  32,  32 }, {  256,   64,  32,  32 }, {  288,   64,  32,  32 }, {  320,   64,  32,  32 }, {  352,   64,  32,  32 }, {  384,   64,  32,  32 } },
    [GG_OVERLAY_ROAD] = { {    0,   96,  32,  32 }, {   32,   96,  32,  32 }, {   64,   96,  32,  32 }, {   96,   96,  32,  32 }, {  128,   96,  32,  32 }, {  160,   96,  32,  32 }, {  192,   96,  32,  32 }, {  224,   96,  32,  32 }, {  256,   96,  32,  32 }, {  288,   96,  32,  32 }, {  320,   96,  32,  32 }, {  352,   96,  32,  32 }, {  384,   96,  32,  32 } },
    [GG_OVERLAY_SAND] = { {    0,  128,  32,  32 }, {   32,  128,  32,  32 }, {   64,  128,  32,  32 }, {   96,  128,  32,  32 }, {  128,  128,  32,  32 }, {  160,  128,  32,  32 }, {  192,  128,  32,  32 }, {  224,  128,  32,  32 }, {  256,  128,  32,  32 }, {  288,  128,  32,  32 }, {  320,  128,  32,  32 }, {  352,  128,  32,  32 }, {  384,  128,  32,  32 } },
    [GG_OVERLAY_DESERT] = { {    0,  160,  32,  32 }, {   32,  160,  32,  32 }, {   64,  160,  32,  32 }, {   96,  160,  32,  32 }, {  128,  160,  32,  32 }, {  160,  160,  32,  32 }, {  192,  160,  32,  32 }, {  224,  160,  32,  32 }, {  256,  160,  32,  32 }, {  288,  160,  32,  32 }, {  320,  160,  32,  32 }, {  352,  160,  32,  32 }, {  384,  160,  32,  32 } },
};

// --- font: fixed cells, proportional advances ---
#define GG_FONT_FIRST   32
#define GG_FONT_LAST    126
#define GG_FONT_CELL_W  7
#define GG_FONT_CELL_H  17
#define GG_FONT_COLS    16
static const uint8_t GG_FONT_ADV[GG_FONT_LAST - GG_FONT_FIRST + 1] = {
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
};

#endif // GG_ATLAS_H
