// gg_atlas.h - GENERATED by tools/make_atlas.py, do not edit.
//
// Where every sprite sits inside the four atlas textures in assets/.
//
// Art: LPC Revised (github.com/ElizaWy/LPC), OGA-BY 3.0 / CC-BY 3.0.
// Font: VT323 by Peter Hull, SIL Open Font License 1.1.
// Per-asset attribution is in assets/CREDITS.md, which this script also writes.

#ifndef GG_ATLAS_H
#define GG_ATLAS_H

#include <stdint.h>
#include "core/gg_ids.h"

typedef struct { int16_t x, y, w, h; } gg_rect;

static const gg_rect GG_TILE_RECT[GG_TILE_COUNT] = {
    [GG_TILE_GRASS] = {    0,    0,  32,  32 },
    [GG_TILE_GRASS_WORN] = {   32,    0,  32,  32 },
    [GG_TILE_DIRT] = {   64,    0,  32,  32 },
    [GG_TILE_EARTH_DARK] = {   96,    0,  32,  32 },
    [GG_TILE_FARMLAND] = {  128,    0,  32,  32 },
    [GG_TILE_ROAD] = {  160,    0,  32,  32 },
    [GG_TILE_SAND] = {  192,    0,  32,  32 },
    [GG_TILE_DESERT] = {  224,    0,  32,  32 },
    [GG_TILE_WATER] = {    0,   32,  32,  32 },
    [GG_TILE_WATER_DEEP] = {   32,   32,  32,  32 },
    [GG_TILE_MOUNTAIN] = {   64,   32,  32,  32 },
    [GG_TILE_CLIFF] = {   96,   32,  32,  32 },
};

static const gg_rect GG_PROP_RECT[GG_PROP_COUNT] = {
    [GG_PROP_TREE_OAK] = {    0,    0,  96, 128 },
    [GG_PROP_TREE_ELM] = {   96,    0,  96, 128 },
    [GG_PROP_TREE_TALL] = {  192,    0,  96, 128 },
    [GG_PROP_TREE_PINE] = {  288,    0,  96, 128 },
    [GG_PROP_TREE_FIR] = {  384,    0,  96, 128 },
    [GG_PROP_TREE_BARE] = {    0,  128,  96, 160 },
    [GG_PROP_STUMP] = {   96,  128,  32,  32 },
    [GG_PROP_BUSH_ROUND] = {  128,  128,  32,  64 },
    [GG_PROP_BUSH_LEAFY] = {  160,  128,  32,  64 },
    [GG_PROP_BUSH_CONIFER] = {  192,  128,  32,  64 },
    [GG_PROP_REEDS] = {  224,  128,  32,  64 },
    [GG_PROP_FERN] = {  256,  128,  32,  64 },
    [GG_PROP_LILYPAD] = {  288,  128,  32,  32 },
    [GG_PROP_CATTAILS] = {  320,  128,  32,  64 },
};

#define GG_ACTOR_FRAME   64
// Top-left of each actor's block; add facing*FRAME to y, frame*FRAME to x.
static const gg_rect GG_ACTOR_RECT[GG_ACTOR_COUNT] = {
    [GG_ACTOR_AVATAR] = {    0,    0,  64,  64 },
    [GG_ACTOR_GUARD] = {    0,  256,  64,  64 },
    [GG_ACTOR_MERCHANT] = {    0,  512,  64,  64 },
    [GG_ACTOR_HEALER] = {    0,  768,  64,  64 },
    [GG_ACTOR_MAGE] = {    0, 1024,  64,  64 },
    [GG_ACTOR_ELDER] = {    0, 1280,  64,  64 },
};

// --- font: fixed cells, proportional advances ---
#define GG_FONT_FIRST   32
#define GG_FONT_LAST    126
#define GG_FONT_CELL_W  7
#define GG_FONT_CELL_H  17
#define GG_FONT_COLS    16
static const uint8_t GG_FONT_ADV[GG_FONT_LAST - GG_FONT_FIRST + 1] = {
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
     6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
};

#endif // GG_ATLAS_H
