// gg_font.h - the baked bitmap font.
//
// The glyph sheet is generated by tools/make_atlas.py from a real TTF, so the
// game needs no font library and no font installed. Cells are uniform; the
// advances are not, because VT323 is proportional - see GG_FONT_ADV.
#ifndef GG_FONT_H
#define GG_FONT_H

#include "core/gg_common.h"
#include "gfx/gg_atlas.h"

// Safe to call for more than one renderer: the debug view has its own window,
// and each renderer needs its own texture.
bool gg_font_init(SDL_Renderer *ren);
void gg_font_quit_renderer(SDL_Renderer *ren);
void gg_font_quit(void);

void gg_font_draw(SDL_Renderer *ren, int x, int y, SDL_Color c, const char *text);
void gg_font_printf(SDL_Renderer *ren, int x, int y, SDL_Color c,
                    SDL_PRINTF_FORMAT_STRING const char *fmt, ...)
    SDL_PRINTF_VARARG_FUNC(5);

// Width of `text` in pixels, using the same advances gg_font_draw will.
int gg_font_width(const char *text);

static inline int gg_font_height(void) { return GG_FONT_CELL_H; }

// Draws `text` centred on `cx`.
void gg_font_center(SDL_Renderer *ren, int cx, int y, SDL_Color c, const char *text);

#endif // GG_FONT_H
